# H2 configuration
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
#spring.datasource.username=sa
#spring.datasource.password=

# PostgreSQL configuration (uncomment to use)
 spring.datasource.driver-class-name=org.postgresql.Driver
 spring.datasource.url=jdbc:postgresql://localhost:5432/posts
 spring.datasource.username=postgres
 spring.datasource.password=masterkey