# PostgreSQL configuration (uncomment to use)
 spring.datasource.driver-class-name=org.postgresql.Driver
 spring.datasource.url=jdbc:postgresql://localhost:5432/posts
 spring.datasource.username=postgres
 spring.datasource.password=masterkey2